#!/bin/bash

# Setup script for flowlint-screenshots repository
# Creates directory structure for n8n workflow screenshots

set -e  # Exit on error

echo "🚀 Setting up flowlint-screenshots repository structure..."

# Check if we're in the right directory
if [ ! -d ".git" ]; then
    echo "❌ Error: Not in a git repository. Please run this from flowlint-screenshots repo root."
    exit 1
fi

# Create main screenshots directory
mkdir -p screenshots

# Create category directories based on awesome-n8n-templates structure
categories=(
    "AI_Research_RAG_and_Data_Analysis"
    "Airtable"
    "Database_and_Storage"
    "Discord"
    "Forms_and_Surveys"
    "Gmail_and_Email_Automation"
    "Google_Drive_and_Google_Sheets"
    "HR_and_Recruitment"
    "Instagram_Twitter_Social_Media"
    "Notion"
    "OpenAI_and_LLMs"
    "Other_Integrations_and_Use_Cases"
    "PDF_and_Document_Processing"
    "Slack"
    "Telegram"
    "WhatsApp"
    "WordPress"
    "devops"
)

echo "📁 Creating category directories..."
for category in "${categories[@]}"; do
    mkdir -p "screenshots/$category"
    # Add .gitkeep to track empty directories
    touch "screenshots/$category/.gitkeep"
    echo "  ✅ Created screenshots/$category/"
done

# Create README.md
echo "📝 Creating README.md..."
cat > README.md << 'EOF'
# FlowLint Screenshots

Automated screenshot repository for n8n workflow marketing automation.

## 📁 Structure

```
screenshots/
├── AI_Research_RAG_and_Data_Analysis/
├── Airtable/
├── Database_and_Storage/
├── Discord/
├── Forms_and_Surveys/
├── Gmail_and_Email_Automation/
├── Google_Drive_and_Google_Sheets/
├── HR_and_Recruitment/
├── Instagram_Twitter_Social_Media/
├── Notion/
├── OpenAI_and_LLMs/
├── Other_Integrations_and_Use_Cases/
├── PDF_and_Document_Processing/
├── Slack/
├── Telegram/
├── WhatsApp/
├── WordPress/
└── devops/
```

## 🔗 Public URL Format

Screenshots are accessible via GitHub raw content URLs:

```
https://raw.githubusercontent.com/nitramyloh/flowlint-screenshots/main/screenshots/{category}/{filename}.png
```

### Example:
```
https://raw.githubusercontent.com/nitramyloh/flowlint-screenshots/main/screenshots/Gmail_and_Email_Automation/auto-label-gmail.png
```

## 📸 Screenshot Naming Convention

Workflow filenames are converted to screenshot filenames:

- **Original**: `Auto-label incoming Gmail messages with AI nodes.json`
- **Screenshot**: `auto-label-incoming-gmail-messages.png`

**Rules:**
- Lowercase
- Spaces → hyphens (`-`)
- Remove special characters
- Max 50 characters
- Remove redundant suffixes like "with AI", "using OpenAI"

## 🤖 Automation

Screenshots are automatically generated and committed by n8n workflows:

1. **Screenshot Generator Workflow** - generates PNG from n8n workflow
2. **GitHub Commit** - uploads to this repo via GitHub API
3. **URL Distribution** - uses public URL in social media posts and landing pages

## 📊 Stats

- **Total Categories**: 18
- **Total Screenshots**: (updated automatically)
- **Average Size**: ~200-400 KB per screenshot
- **Format**: PNG (1920x1080)

## 🔧 Maintenance

This repository is automatically managed. Manual edits should be minimal.

To regenerate all screenshots:
```bash
# From n8n instance
npm run generate-all-screenshots
```

## 📄 License

Screenshots are derived from workflows in [awesome-n8n-templates](https://github.com/nitramyloh/awesome-n8n-templates).
All rights to original workflows belong to their respective creators.

---

**Generated by**: FlowLint Marketing Automation System
**Last Updated**: $(date +%Y-%m-%d)
EOF

# Create .gitignore
echo "🚫 Creating .gitignore..."
cat > .gitignore << 'EOF'
# macOS
.DS_Store
.AppleDouble
.LSOverride

# Thumbnails
._*

# Files that might appear in the root of a volume
.DocumentRevisions-V100
.fseventsd
.Spotlight-V100
.TemporaryItems
.Trashes
.VolumeIcon.icns
.com.apple.timemachine.donotpresent

# Windows
Thumbs.db
ehthumbs.db
Desktop.ini

# Linux
*~

# Temporary files
*.tmp
*.temp
*.log

# Node modules (if we add scripts)
node_modules/
package-lock.json

# Environment variables
.env
.env.local
EOF

# Create a sample placeholder image info file
echo "ℹ️  Creating info file..."
cat > screenshots/INFO.txt << 'EOF'
Screenshot Storage Information
==============================

This directory contains automated screenshots of n8n workflows.

Format: PNG (1920x1080)
Quality: 90%
Generation: Puppeteer via n8n workflow
Frequency: On-demand

Each screenshot shows the complete n8n workflow canvas with all nodes visible.
EOF

# Git add all files
echo "📦 Staging files for commit..."
git add .

# Show status
echo ""
echo "✅ Setup complete!"
echo ""
echo "📊 Directory structure created:"
tree -L 2 screenshots/ 2>/dev/null || find screenshots -type d | head -20

echo ""
echo "📋 Files ready to commit:"
git status --short

echo ""
echo "🎯 Next steps:"
echo "1. Review the changes: git status"
echo "2. Commit: git commit -m 'Initial repository structure'"
echo "3. Push: git push origin main"
echo ""
echo "💡 Tip: Make sure the repository is set to PUBLIC in GitHub settings"
echo "   (Settings → Danger Zone → Change repository visibility → Make public)"
EOF

chmod +x setup-screenshots-repo.sh

echo "✅ Setup script created!"
